---
title: "Powtórka z analizy stochastycznej"
author: "Adam Pytel"
date: "22 października 2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Wstęp

Dzisiejsze zajęcia mają za zadanie odświeżyć wiadomości poznane na przedmiocie
"Podstawy Analizy Stochastycznej" i naświetlić rolę jaką analiza stochastyczna 
odgrywa we współczesnej matematyce finansowej.

Głównym tematem będzie zagadnienie zamiany miary szeroko wykorzystywane 
przy wycenie instrumentów pochodnych.

## Podstawowa różnica w miarach

Każda rozważana miara martyngałowa $P^\ast$ jest jedynie miarą techniczną,
narzędziem pozwalającym oderwać się od zagadnienia modelowania dryfu. To przestrzeń
probabilistyczna z miarą rzeczywistą ma odzwierciedlać widzianą rzeczywistość.
Punkt widzenia jest subiektywny, dlatego też każdy inwestor czy dealer, jeżeli
byłby w stanie opisać tą miarę, najprawdopodbniej opisałby ją w nieco inny sposób,
niekoniecznie zbieżny z innym dealerem/traderem.

**Uwaga:** Żaden dealer nie posługuje się na codzień pojęciem miary probabilistycznej ;).

## Zamiana miary a martyngały cz.1 {.smaller}

**Zadanie 1.** Rozważmy dwie równoważne miary probabilistyczne $\mathbb{P}$ i $\mathbb{Q}$ na przestrzeni probabilistycznej z filtracją $(\Omega, \mathcal{F}, \mathbb{F})$, gdzie $\mathcal{F}_0$ jest $\sigma$-ciałem trywialnym, a $T>0$ jest ustalonym horyzontem czasowym. Definiujemy proces $\eta$:
$$\eta_t:=\mathbb{E}_{\mathbb{P}}\left(\frac{d\mathbb{Q}}{d\mathbb{P}}\mid \mathcal{F}_t\right),\quad t\in[0,T]. $$

- Sprawdź bezpośrednio z definicji, że proces $\eta_t,\ t\in[0,T]$ jest ściśle dodatnim $\mathbb{P}$-martyngałem względem filtracji $\mathbb{F}$ takim, 
że $\eta_0=1$.
- Wykorzystując abstrakcyjną formułę Bayesa, wykaż, że $\mathbb{F}$-adaptowany proces $(M_t)_{[0,T]}$ jest $\mathbb{Q}$-martyngałem względem $\mathbb{F}$ wtedy i tylko wtedy, gdy proces $(M_t\eta_t)_{[0,T]}$ jest $\mathbb{P}$-martyngałem.

## Zamiana miary a martyngały cz.2 {.smaller}

**Rozwiązanie:** 
Wiedząc, że gęstość Radona-Nikodyma miar probabilistycznych jest zmienną losową nieujemną, otrzymujemy z czysto probabilistycznego faktu, że $\eta$ jest martyngałem nieujemnym. Załóżmy jednak, że dla pewnego $t>0$ zbiór
$$N = \{\eta_t = 0\} $$
ma miarę $\mathbb{P}$ dodatnią. Oznacza to, że 
$$
\begin{align}
0 & = \mathbb{E}_{\mathbb{P}}\left(\eta_t \mathbb{I}_N\right) = \mathbb{E}_{\mathbb{P}}\left(\mathbb{E}_{\mathbb{P}}\left(\frac{d\mathbb{Q}}{d\mathbb{P}}\mid \mathcal{F}_t\right) \mathbb{I}_N\right) = \mathbb{E}_{\mathbb{P}}\left(\mathbb{E}_{\mathbb{P}}\left(\frac{d\mathbb{Q}}{d\mathbb{P}} \mathbb{I}_N\mid \mathcal{F}_t\right)\right) \\
 & =\mathbb{E}_{\mathbb{P}}\left(\frac{d\mathbb{Q}}{d\mathbb{P}} \mathbb{I}_N\right) = \mathbb{Q}(N)
\end{align}
$$
gdzie pierwsza równość wynika z definicji zbioru $N$, druga z definicji procesu $\eta$, trzecia z przynależności $N\in\mathcal{F}_t$, czwarta z własności warunkowej wartości oczekiwanej, a piąta z definicji gęstości Radona-Nikodyma. Założyliśmy,
że miara $P$ zbioru $N$ jest dodatnia, zatem przez równoważność miar, także miara $Q$ zbioru $N$ jest dodatnia, co stoi w sprzeczności z powyższym ciągiem nierówności.
Stąd dla każdego $t\in[0,T]$ mamy $\mathbb{P}(\eta_t>0)=1$. 

## Zamiana miary a martyngały cz.3 {.smaller}

Skoro $\eta$ jest martyngałem, to posiada nierozróżnialną modyfikację *cadlag*, a ta własność
z argumentem gęstościowym pociąga za sobą ścisłą dodatniość procesu, czyli:
$$\mathbb{P}\left(\forall\,t\in[0,T]\ \eta_t > 0\right)=1.$$

Przejdźmy do dalszej części zadania. Niech $M$ będzie $\mathbb{Q}$-martyngałem.
Wtedy proces $M \eta$ jest $\mathbb{F}$-adaptowany, ponieważ jest iloczynem dwóch procesów adaptowalnych i jest całkowalny, co wynika z nieujemności pochodnej Radona-Nikodyma i własności warunkowej wartości oczekiwanej. Sprawdźmy warunek martyngałowy dla ustalonych $t,s$ takich, że $t\ge s$:
$$
\begin{align}
\mathbb{E}_{\mathbb{P}}\left(M_t \eta_t \mid \mathcal{F}_s\right) = \mathbb{E}_{\mathbb{P}}\left(M_t \eta_T \mid \mathcal{F}_s\right) = \mathbb{E}_{\mathbb{Q}}\left(M_t \mid \mathcal{F}_s\right) \mathbb{E}_{\mathbb{P}}\left(\eta_T \mid \mathcal{F}_s\right) = M_s \eta_s,
\end{align}
$$
gdzie w pierwszej równości skorzystaliśmy z własności teleskopowej w.w.o.,
a w drugim z uogólnionego twierdzenia Bayesa. 

## Zamiana miary a martyngały cz.4 {.smaller}

Zakładając z kolei, że proces $M\eta$
jest $\mathbb{P}$-martyngałem otrzymujemy wprost z uogólnionego twierdzenia Bayesa, że
$$
\begin{align}
\mathbb{E}_{\mathbb{Q}}\left(M_t \mid \mathcal{F}_s\right) & = \frac{\mathbb{E}_{\mathbb{P}}\left(M_t \eta_T \mid \mathcal{F}_s\right)}{\mathbb{E}_{\mathbb{P}}\left(\eta_T \mid \mathcal{F}_s\right)} = \frac{\mathbb{E}_{\mathbb{P}}\left(\mathbb{E}_{\mathbb{P}}\left(M_t\eta_T\mid \mathcal{F}_t\right) \mid \mathcal{F}_s\right)}{\eta_s} \\ & = \frac{\mathbb{E}_{\mathbb{P}}\left(M_t \ \mathbb{E}_{\mathbb{P}}\left(\eta_T\mid \mathcal{F}_t\right) \mid \mathcal{F}_s\right)}{\eta_s} 
= \frac{\mathbb{E}_{\mathbb{P}}\left(M_t \ \eta_t \mid \mathcal{F}_s\right)}{\eta_s}
 \\ & = \frac{M_s \eta_s}{\eta_s} = M_s,
\end{align}
$$
co ostatecznie dowodzi tezy z zadania.

## Tworzenie równoważnych miar martyngałowych cz.1 {.smaller}

Z poprzedniego zadania możemy wnioskować, że biorąc dowolną ściśle dodatnią, $\mathcal{F}_T$-mierzalną i $\mathbb{P}$-całkowalną zmienną losową $Z$ możemy utworzyć poprawną
zamianę miary na nową miarę równoważną $\mathbb{Q}$ po przez gęstość Radona-Nikodyma:
$$\frac{\mathbb{dQ}}{\mathbb{dP}} = \frac{Z}{\mathbb{E}_{\mathbb{P}}(Z)}.$$
Jak widzieliśmy na wykładzie,
zamiana miary z rzeczywistej na martyngałową usuwa nam nieznany dryf, odzwierciedlający często subiektywne opinie inwestorów. Technika zamiany miary
pozwala również na sformułowanie problemu wyceny w jezyku innych *numeraire* aniżeli
standardowego (i często abstrakcyjnego) "rachunku bankowego".

## Tworzenie równ. miar mart. cz.2 {.smaller}

**Zadanie 2.** Niech $\mathbb{P}$ i $\mathbb{Q}$ będą dwoma równoważnymi miarami
martyngałowymi odpowiadającymi *numeraire* $Z^1$ i $Z^2$. Ogólna postać zamiany
miary jest następująca:
$$\frac{\mathbb{dQ}}{\mathbb{dP}} = \frac{Z^1_0}{Z^2_0} \cdot \frac{Z^2_T}{Z^1_T}.$$

1. Znajdź postać zamiany miary w modelu Blacka-Scholesa przyjująć, że miara $\mathbb{P}^\ast$ odpowiada procesowi rachunku bankowego, a $\mathbb{Q}$ procesowi cen akcji $S$. Znajdź dynamikę zdyskontowanego procesu $B^\ast = \frac{B}{S}$ przy mierze $\mathbb{P}$ oraz mierze $\mathbb{Q}$.  
2. Znajdź zamianę miary $\frac{\mathbb{dP}_T}{\mathbb{dP}^\ast}$ w przypadku bezarbitrażowej rodziny cen obligacji wiedząc, że
miara $\mathbb{P}^\ast$ odpowiada procesowi akumulacji kapitału $B$, a miara $\mathbb{P}_T$ odpowiada procesowi ceny obligacji zerokuponowej o terminie zapadalności $T$ (miara ta jest nazywana miarą $T$-forward). Jaką postać przyjmuje
proces $\eta$?

## Tworzenie równ. miar mart. cz.3 {.smaller}

**Rozwiązanie:** Zacznijmy od punktu 1. W modelu Blacka-Scholesa proces rachunku
bankowego jest procesem deterministycznym. Wraz z procesem cen akcji oba z nich
w chwili $T$ przyjmują wartość:
$$B_T = e^{r\, T},\quad S_T = S_0 \, e^{(r-\sigma^2/2)\,T + \sigma\,W_T}, $$
gdzie $W$ jest procesem Wienera przy mierze martyngałowej $\mathbb{P}^\ast$.
Korzystając z wzoru na zamianę miary otrzymujemy:
$$\frac{\mathbb{dQ}}{\mathbb{dP}^\ast} = \frac{B_0 \, S_T}{S_0 \, B_T} = e^{ \sigma\,W_T - \frac{\sigma^2\,T}{2}}. $$
Znajdźmy teraz dynamikę procesu $B^\ast$ przy dwóch różnych miarach. 
Rozpoczniemy od znalezienie dynamiki procesu $1/S$ korzystając z lematu Ito:
$$
\begin{align}
d\frac{1}{S_t} & = -\frac{1}{S^2_t}\,dS_t + \frac{1}{2} \frac{2}{S^3_t} d[S]_t = 
\frac{1}{S_t} \left(-r\,dt - \sigma\,dW_t\ + \sigma^2\,dt  \right)\\
& = \frac{1}{S_t} \left((\sigma^2-r)\,dt - \sigma\,dW_t  \right)
\end{align}
$$

## Tworzenie równ. miar mart. cz.4 {.smaller}

Na podstawie stochastycznej wersji lematu Leibnitza mamy:
$$
\begin{align}
d\left(\frac{B}{S}\right)_t & = B_t \,d\left(\frac{1}{S}\right)_t + \frac{1}{S_t}\,dB_t + d[B,1/S]_t = \frac{B_t}{S_t}\left(\sigma^2\,dt - \sigma\,dW_t\right)
\end{align}
$$
Dynamika ta nie zmienia się przy zamianie miary, jednakże proces $W$ nie jest już procesem Wienera. Zatem o ile opis samego procesu nie ulega zmianie, to własności
probabilistyczne/stochastyczne są już inne.
Z twierdzenia Girsanowa wiemy, że proces zadany równością:
$$ W^{\mathbb{Q}}_t = W_t - \int_0^T{\sigma \,dt }$$ 
jest procesem Wienera przy mierze $Q$. To pozwala nam na zapisanie poprzedniego
równania dynamiki w innym języku:
$$
\begin{align}
d\left(\frac{B}{S}\right)_t & = \frac{B_t}{S_t}\left(\sigma^2\,dt - \sigma\,dW_t\right) = \frac{B_t}{S_t}\left(\sigma^2\,dt - \sigma^2 \, dt - \sigma\,dW^{\mathbb{Q}}_t\right) = -\frac{B_t}{S_t}\,dW^{\mathbb{Q}}_t.
\end{align}
$$

## Tworzenie równ. miar mart. cz.5 {.smaller}

Przejdźmy do drugiej części zadania. Tak jak w pierwszym punkcie wystarczy podstawić do wzoru odpowiednie ceny aktywów:
$$\frac{\mathbb{dQ}}{\mathbb{dP}^\ast} = \frac{B_0 \, B(T,T)}{B(0,T) \, B_T} =  \frac{1}{B(0,T) \, B_T}. $$

Proces $\eta$ definiowany jest jako martyngał:
$$
\begin{align}
\eta_t & = \mathbb{E}_{\mathbb{P}^\ast}\left(\frac{d\mathbb{Q}}{d\mathbb{P^\ast}}\mid \mathcal{F}_t\right) = \mathbb{E}_{\mathbb{P^\ast}}\left(\frac{1}{B(0,T) \, B_T}\mid \mathcal{F}_t\right) \\ & = \frac{1}{B(0,T)}\mathbb{E}_{\mathbb{P^\ast}}\left(\frac{B_t}{B(0,T)_t \, B_T}\mid \mathcal{F}_t\right)  = \frac{B(t,T)}{B(0,T)\, B_t}
\end{align}
$$