---
title: "Modele chwilowej stopy procentowej"
author: "Adam Pytel"
date: "7 listopada 2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

\DeclareMathOperator{\sign}{sign}
\newcommand{\E}{\mathbb{E}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\P}{\mathbb{P}}
\newcommand{\Ff}{\mathcal{F}}

## Wstęp {.smaller}

Pierwsza generacja modeli stóp procentowych używana do wyceny instrumentów finansowych
powstała tuż po publikacji modelu Blacka-Scholesa. Modele te skupiły się na opisie
chwilowej stopy procentowej. Głównym celem tych modeli było uzyskanie analitycznych
wzorów na cenę instrumentów pochodnych, bądź prostych i szybkich algorytmów
umożliwiających wycenę tychże instrumentów (drzewa dwu- i trójmianowe, metoda
różnic skończonych). 

Początkowo modele służyły traderom do wyceny obligacji (na podstawie paru płynnych
serii kalibrowano model i szacowano cenę mniej płynnych serii). Gdy zainteresowanie
traderów przeniosło się z rynku obligacji na instrumenty pochodne, pierwsza
generacja modeli (potocznie zwana modelami równowagi bądź *equilibrium*)
przestała spełniać swoje podstawowe funkcje. Nie mniej jednak modele te nadal
są wykorzystywane w różnych obszarach, m. in. w zarządzaniu ryzykiem, prognozach
i stress testach.

## Model CIR - wstęp

Na wykładzie został zaprezentowany przykładowy model chwilowej stopy procentowej - model Vasicka. W modelu tym chwilowa stopa procentowa ma rozkład gaussowski.
W związku z tym prawdopodobieństwo tego, że stopa procentowa będzie poniżej 0
jest dodatnie. Taka własność modelu w czasach w których obserwowane stopy procentowe
były na poziomie $[4\%, 15\%]$ była uważana za wadę modelu (w obecnych czasach
na niektórych walutach jest to raczej zaletą niż wadą). Ponadto, jak wiadomo,
rozkład gaussowski nie jest rozkładem ciężkoogonowym, podczas gdy empiryczne
rozkłady stóp procentowych charakteryzują się ciężkimi ogonami.

Model CIR w części rozwiązuje te problemy (choć zauważona to raczej post factum).


## Model CIR - uproszczenie cz.1

**Zadanie 1.** Załóżmy, że proces chwilowej stopy procentowej zdefiniowany jest
w następujący sposób:
$$ r_t = \left(\frac{\sigma\,W_t}{2} \right)^2, \quad \forall\,t\in [0,T],$$
gdzie $W$ jest procesem Wienera przy mierze martyngałowej spot oraz $\sigma>0$.

1. Wyznacz stochastyczne równanie różniczkowe opisujące dynamikę chwilowej stopy procentowej.
2. Jaki rozkład ma zmienna losowa $r_t$.

## Model CIR - uproszczenie cz.2 {.smaller}

**Rozwiązanie:** Z definicji wiemy, że $r_t \ge 0$ dla dowolnego $t\in[0,T]$ $\mathbb{P}^\ast$-p.n.. 
Na mocy wzoru Ito dla funkcji $f(x) = \frac{\sigma^2}{4}x^2$ mamy:

$$
\begin{align}
dr_t & = 2\cdot\frac{\sigma^2}{4} W_t\,dW_t + \frac{1}{2}\cdot 2 \frac{\sigma^2}{4}\,dt
\\ & = \frac{\sigma^2}{4}\,dt + \sigma\cdot \frac{\sigma}{2}|W_t|\cdot\sign{W_t}\,dW_t
\\ & = \frac{\sigma^2}{4}\,dt + \sigma\cdot \sqrt{r_t}\cdot\sign{W_t}\,dW_t  
\end{align}
$$
Wykażmy, że proces $B_\cdot = \int_0^\cdot{\sign{W_u}\,dW_u}$ jest ruchem Browna przy mierze martyngałowej $\mathbb{P}^\ast$. Z jednej z wersji twierdzenia Levy'ego wiemy, 
że proces $B$ jest ruchem Browna jeżeli jest ciągłym $\mathbb{P}$-martygałem lokalnym o nawiasie
skośnym będącym procesem deterinistycznym równym $\langle B\rangle_t = t$.
Całka stochastyczna względem procesu Wienera jest martyngałem lokalnym. 
Ponadto nawias skośny procesu $B$ wynosi:
$$\langle B\rangle_t = \int_0^t{(\sign{W_u})^2\,du} = t. $$


## Model CIR - uproszczenie cz.3

Oznacza to, że $B$ jest ruchem Browna. Stąd proces $r$ spełania równanie:
$$dr_t = \frac{\sigma^2}{4}\,dt + \sigma \sqrt{r_t}\,dB_t$$
Jest to szczególny przypadek równania na proces CIR. Z definicji procesu $r$ wnioskujemy, że zmienna losowa $r_t$ ma przeskalowany rozkład $\chi^2(1)$, ponieważ:
$$r_t = \left(\frac{\sigma\cdot W_t}{2}\right)^2 \stackrel{d}{=} \frac{\sigma^2\,t}{4}N^2,$$
gdzie $N\sim\mathcal{N}(0,1)$, czyli $N^2\sim\chi^2(1)$. 


## Mocel CIR - cena obligacji cz.1 {.smaller}

W poprzednim przykładzie rozważaliśmy uproszczoną wersję modelu CIR. Teraz
spróbujemy znaleźć cenę obligacji zerokuponowej w przypadku pełnej wersji modelu.

**Zadanie 2.** Niech $r$ będzie procesem chwilowej stopy procentowej zadanym stochastycznym równaniem różniczkowym przy mierze martyngałowej $\mathbb{P}^\ast$:
$$dr_t = a\left(b - r_t\right)\,dt + \sigma \sqrt{r_t}\,dW_t.\quad r_0 = r. $$
Znajdź cenę obligacji zerokuponowej na chwilę $t$.

**Rozwiązanie:** Ustalmy zapadalność obligacji zerokuponowej na $T>0$. 
Proces $r$ posiada własność Markowa, ponieważ dryf i czynnik dyfuzyjny są funkcjami
lokalnie lipschitzowskimi (ta własność wraz z dodatnią określonością czynnika dyfuzyjnego zapewnia własność Markowa). 
Cena obligacji zerokuponowej zadana jest przez warunkową wartość oczekiwaną:
$$B(t,T) = \E\left(e^{-\int_t^T{r_u\,du}}\mid\Ff_t\right)= \E\left(e^{-\int_t^T{r_u\,du}}\mid r_t\right) = v(r_t,t), \quad \forall t\in[0,T]. $$

## Mocel CIR - cena obligacji cz.2 {.smaller}

Z twierdzenia Feynmana-Kaca (bądź z twierdzenia o strukturze) wiemy, że powyższa warunkowa wartość oczekiwana jest rozwiązaniem poniższego równania różniczkowego cząstkowego (dokładniej funkcja v):
$$
\left\{\begin{array}{lc} \frac{\partial }{\partial t}v(x,t) + a(b-x)\frac{\partial}{\partial x}v(x,t) + \frac{1}{2}\sigma^2x\frac{\partial^2}{\partial x^2}v(x,t) - x\,v(x,t) = 0 \\ v(x,T) = 1, \quad\forall x\in\R. \end{array} \right.
$$

Z drugiej jednak strony proces $r$ zadaje afiniczną strukturę terminową, ponieważ
$\mu(t,x) = a\cdot(b-x)$ jest funkcją afiniczną oraz $\Sigma^2(t,x)=\sigma^2\cdot x$ jest również funkcją afiniczną. 
Zatem z twierdzenia o równoważych warunkach na ATS wynika, że mamy doczynienia z modelem ATS. Stąd istnieją funkcje deterministyczne $n, m$ takie, że:
$$B(t,T) =e^{m(t,T) - n(t,T)\cdot r_t}, \quad \forall t\in[0,T]. $$
Podstawiając tą postać do równania różniczkowego cząstkowego otrzymamy
układ równań różniczkowych zwyczajnych.

## Mocel CIR - cena obligacji cz.3 {.smaller}

Obliczmy w tym celu poszczególne pochodne cząstkowe:
$$
\begin{align}
\frac{\partial }{\partial t}v(x,t) & = v(x,t)\left(m'(t,T) - n'(t,T) x \right),\\ 
\frac{\partial}{\partial x}v(x,t) & =  - n(t,T)\,v(x,t)  ,\\
\frac{\partial^2}{\partial x^2}v(x,t) & = n^2(t,T)\,v(x,t)
\end{align} 
$$

Podstawiając powyższe wartości do r.r.cz. otrzymamy:

$$
\left\{\begin{array}{lc} 
v(x,t)\cdot\left(m'(t,T) - n'(t,T)\cdot x  - a(b-x) n(t,T) + \frac{1}{2}\sigma^2x\,n^2(t,T) - x\right) = 0 \\ 
v(x,T) = 1, \quad\forall x\in\R. 
\end{array} \right.
$$

## Mocel CIR - cena obligacji cz.4 {.smaller}

Grupując wyrazy przy $x$ oraz $1$ otrzymujemy (z liniowej niezależności i ścisłej dodatniości $v$), że funkcja $m, n$ spełniają następujący układ równań różniczkowych cząstkowych:

$$
\left\{\begin{array}{ll} 
0 = m'(t,T) - a\, b\, n(t,T), & m(T,T) = 0 \\
0 = -n'(t,T)  + a n(t,T) + \frac{1}{2}\sigma^2n^2(t,T) - 1, & n(T,T) = 0 
\end{array} \right.
$$

Rozwiążmy ten układ r.r.z. Zauważmy, że znając funkcję $n$ będziemy w stanie w łatwy sposób odzyskać postać funkcji $m$ po przez przecałkowanie pierwszego równania, tzn.:
$$a\, b\, \int_t^T{n(u,T)\,du} = \int_t^T{m'(u,T)\,du} = m(T,T)-m(t,T) = -m(t,T).$$
Zajmijmy się zatem drugim równaniem.

## Mocel CIR - cena obligacji cz.5 {.smaller}

Drugie równanie jest równaniem Ricattiego. Dla takiego równania wystarczy znaleźć jedno szczególne rozwiązanie r.r.z, by następnie odzyskać rozwiązanie ogólne r.r.z.
Jednym z rozwiązań szczególnych jest rozwiązanie stałe $n^*\equiv c$, gdzie $c$ jest rozwiązaniem równania kwadratowego:
$$a c + \frac{1}{2}\sigma^2c^2(t,T) - 1=0,$$
czyli $c = \frac{-a\pm \gamma }{\sigma^2}$, gdzie $\gamma:= \sqrt{a^2+2\sigma^2}$.
Wybierzmy rozwiązanie dodatnie, czyli $c= \frac{\gamma - a}{\sigma^2}$. Znalezienie
rozwiązania szczególnego sprowadza równanie Ricattiego do równania Bernoulliego
po przez zadanie $n(t,T) = n^*(t,T) + \frac{1}{k(t)}$. Funkcja $k$ spełnia równanie:
$$k'(t) + (a + \sigma^2\,n^*(t,T)) k(t) = -\frac{\sigma^2}{2}, $$
co po rozwinięciu daje:

$$k'(t) + \gamma\, k(t) = \frac{\sigma^2}{2} \Leftrightarrow \frac{k'(t)}{k(t)+\frac{\sigma^2}{2\gamma}} = -\gamma $$

## Mocel CIR - cena obligacji cz.6 {.smaller}

Funkcja $k$ przyjmuje więc postać:

$$k(t) = A\,e^{-\gamma\,t} - \frac{\sigma^2}{2\gamma},\quad \textrm{gdzie } A<0.$$

Warunek końcowy wymusza zależność:
$$0 = n(T,T) = \frac{\gamma - a}{\sigma^2} + \frac{2\gamma e^{\gamma T}}{2\gamma\,A - \sigma^2 e^{\gamma T}}$$
Przekształcając obie strony równania dostajemy:

$$A =\frac{\sigma^2}{2\gamma}\,e^{\gamma\, T} + \frac{\sigma^2\,e^{\gamma\, T}}{a-\gamma} =\sigma^2\,e^{\gamma\, T}\frac{a+\gamma}{2\gamma(a-\gamma)}=-e^{\gamma\, T}\frac{(a+\gamma)^2}{4\gamma} $$

## Mocel CIR - cena obligacji cz.7 {.smaller}

Ostatecznie funkcja $n$ przyjmuje postać:
$$
\begin{align}
n(t,T) & = \frac{\gamma - a}{\sigma^2} - \frac{2\gamma \, e^{\gamma\,t}}{\frac{(\gamma + a)^2}{2}\,e^{\gamma\,T} + \sigma^2\,e^{\gamma\,t}} =  \frac{\gamma - a}{\sigma^2} - \frac{2\gamma \, e^{-\gamma\,(T-t)}}{\frac{(\gamma + a)^2}{2} + \sigma^2\,e^{-\gamma\,(T-t)}} \\
 & = \frac{(\gamma+a)\sigma^2 + (\gamma-a)\,\sigma^2\,e^{-\gamma\,(T-t)}-2\gamma\sigma^2\,e^{-\gamma\,(T-t)}}{\sigma^2\left(\frac{(\gamma + a)^2}{2} + \sigma^2\,e^{-\gamma\,(T-t)}\right)} = \\
 & = \frac{(\gamma + a)\left(1-\,e^{-\gamma\,(T-t)}\right)}{\frac{(\gamma + a)^2}{2} + \sigma^2\,e^{-\gamma\,(T-t)}} = \frac{2\left(1-\,e^{-\gamma\,(T-t)}\right)}{(\gamma + a) + (\gamma-a)\,e^{-\gamma\,(T-t)}} \\
 & = \frac{2\left(e^{\gamma\,(T-t)}-1\right)}{(\gamma+a)\left(e^{\gamma\,(T-t)}-1\right) + 2\gamma}
\end{align}
$$
podczas gdy funkcja $m$ zadana jest wzorem:
$$m(t,T) = \frac{2\,a\,b}{\sigma^2}\ln\left(\frac{2\gamma e^{(\gamma+a)(T-t)/2}}{(\gamma+a)\left(e^{\gamma\,(T-t)}-1\right) + 2\gamma}\right).$$

## Model CIR - równanie na funkcję przejścia  cz.1 {.smaller}

**Zadanie 3.** Znajdź równanie różniczkowe cząstkowe opisujące gęstość prawdopodobieństwa przejścia procesu $r$ w modelu CIR.

**Rozwiązanie:** Oznaczmy przez $P$ funkcję prawdopodobieństw przejścia procesu $r$,
tzn. 
$$ P(r,s,B,t) = \P^\ast(r_t\in B\mid r_s=r),\quad \forall t\ge s\ge 0\ \forall r\ge0 \ \forall B\in\mathcal{B}(\R_+)$$
i niech $p$ będzię funkcją gęstości. Wiemy, że dla procesu Ito $X$ opisanym stochastycznym równaniem różniczkowym:
$$dX_t = \mu(X_t)\,dt + \Sigma(X_t)\, dW_t$$
funkcja $p$ spełnia równanie różniczkowe cząstkowe Fokkera-Plancka (zwane również progresywnym równaniem Kołmogorowa):
$$\frac{\partial}{\partial t}p(x,t) + \frac{\partial}{\partial x}\left(\mu(x)\,p(x,t)\right) - \frac{\partial^2}{\partial x^2}\left(\frac{\Sigma^2(x)}{2}p(x,t)\right) = 0. $$

## Model CIR - równanie na funkcję przejścia  cz.2 {.smaller}

Podstawiając do równania współczynnik dryfu i dyfuzji z modelu CIR otrzymujemy:
$$\frac{\partial}{\partial t}p(x,t) + \left(a(b-x) -\sigma^2\right)\frac{\partial}{\partial x}p(x,t) - \frac{\sigma^2}{2} x\, \frac{\partial^2}{\partial x^2}p(x,t) = 0$$

## Model CIR - równanie na funkcję przejścia  cz.3 {.smaller}

**Zadanie dodatkowe 4 (2 Pkt).** Udowodnij, że funkcja $p$ z poprzedniego zadania
zadana jest wzorem:
$$p(x,t;y,s) = c\, e^{-u-v \,\left(\frac{u}{v} \right)^{q/2}} I_q\left(2\sqrt{u\,v}\right),  $$
gdzie 
$$ 
\begin{align}
c & = \frac{2 a}{\sigma^2\left(1-e^{-a(t-s)}\right)}, \\
u & = c\,x\,e^{-a(t-s)}, \\
v & = c \, y,\\
q & = \frac{2\,a\,b}{\sigma^2}-1,\\
I_q(z) & = \left(\frac{z}{2}\right)^q\,\sum_{k=0}^\infty{\frac{(z^2/4)^k}{k!\,\Gamma(q+k+1)}} 
\end{align}.
$$

## Wycena opcji na obligacje cz.1 {.smaller}

**Zadanie 5.** Rozważmy model o afinicznej strukturze terminowej. Znajdź cenę
opcji call o zapadalności $T$ na obligację zerokuponową o zapadalności $U>T$.
W zadaniu załóż, że krzywa dyskontowa jest taka sama jak krzywa projekcyjna (
do dyskontowania używamy krzywej odzyskanej z obligacji).

**Rozwiązanie:** Wypłata w opcji call na obligację wynosi:
$$X=(B(T,U) - K)^+ = (B(T,U) - K) \mathbb{I}_D , $$
gdzie $K>0$ oraz $D = \left\{B(T,U) > K \right\}$. Z klasycznej teorii wyceny
dostajemy, że
$$
\small
\begin{align}
\pi_t(X) & = B_t \E_{\P^\ast}\left(\frac{1}{B_T}(B(T,U)-K)\mathbb{I}_D\mid\Ff_t\right) \\
& = 
B_t\,\E_{\P^\ast}\left(\E_{\P^\ast}\left(\frac{\mathbb{I}_D}{B_U}\mid\Ff_T\right)\mid\Ff_t\right) - K\, B_t\,B(0,T)\E_{\P^\ast}\left(\frac{\mathbb{I}_D}{B_T\,B(0,T)}\mid\Ff_t\right) \\
& = B_t\,B(0,U)\E_{\P^\ast}\left(\frac{\mathbb{I}_D}{B(0,U)\,B_U}\mid\Ff_t\right) - K\, B_t\,B(0,T)\E_{\P^\ast}\left(\frac{\mathbb{I}_D}{B_T\,B(0,T)}\mid\Ff_t\right)\\
& = B(t,U)\P_{U}(D\mid\Ff_t) - K\,B(t,T)\P_{T}(D\mid\Ff_t)
\end{align}
$$

## Wycena opcji na obligacje cz.2 {.smaller}

Założyliśmy, że nasz model zadaje afiniczną strukturę terminową, co oznacza,
że 
$$D = \left\{B(T,U) > K\right\} =  \left\{e^{m(T,U)-n(T,U)\,r_T} > K\right\} = \left\{\frac{m(T,U)-\ln{K}}{n(T,U)} > r_T\right\},$$
zatem wzór na opcję na obligację przyjmuje postać:
$$\pi_t(X) = B(t,U)\,F_{U}(K^\ast(T,U)\mid\Ff_t) - K\,B(t,T)\,F_{T}(K^\ast(T,U)\mid\Ff_t),$$
gdzie $F_U,F_T$ są dystrybuantami (warunkowymi) zmiennej losowej $r_T$ (względem $\sigma$-ciała $\Ff_t$) odpowiednio przy mierze $\P_U, \P_T$ oraz 
$$K^\ast(U,T) = \frac{m(T,U)-\ln{K}}{n(T,U)}.$$

Wzór ten nieco przypomina wzór Blacka-Scholesa. Czy dystrybuanty warunkowe da się wyznaczyć w łatwy sposób w przypadku modelu Vasicka bądź modelu CIR?
Zadanie nie należy do najłatwiejszych.

## Wycena opcji na obligacje cz.3 {.smaller}

**Zadanie dodatkowe 6. (2 x 2 Pkt). ** Wyznacz dystrybuanty $F_{T}(K^\ast(T,U)\mid r_t)$ oraz $F_{U}(K^\ast(T,U)\mid r_t)$ dla jednego z modeli:

1. Modelu Vasicka.
2. Modelu CIR.

*Wskazówka.* Na początku znajdź (warunkową) transformatę Laplace'a wektora losowego 
$$\left(\int_t^T{r_u\,du}, r_T\right) {\huge\vert} r_t = r$$

## Dynamika $r$ przy mierze $\P_T$ cz.1 {.smaller}

**Zadanie 7.** Znajdź dynamikę chwilowej stopy procentowej przy mierze $\P_T$ dla modelu z afiniczną strukturą terminową. Czy zamiana miary zachowuje afiniczną strukturę terminową?

**Rozwiązanie:** Na ćwiczeniach poznaliśmy technikę zamiany miary. Tezy zadań z listy 2 wykorzystamy do rozwiązania tego zadania. Wiemy, że gęstość Radona-Nikodyma miary
$\P_T$ względem miary $\P^\ast$ wynosi:
$$\frac{d\P_T}{d\P^\ast} = \frac{1}{B(0,T)\,B_T}$$
oraz
$$\eta_t=\frac{d\P_T}{d\P^\ast}{\huge\vert}_{\Ff_t} = \frac{B(t,T)}{B(0,T)\,B_t}.$$
Korzystając z wzoru Ito prawą stronę równania możemy przedstawić jako:
$$\frac{B(t,T)}{B(0,T)\,B_t} = \int_0^t{\ldots\,dt } - \int_0^t{\frac{B(t,T)}{B(0,T)\,B_t}\,n(u,T)\sigma(r_u,u)\,dW_u^\ast}, $$
gdzie pierwsza całka jest równa $0$, ponieważ proces $\eta$ jest $\P^\ast$-martyngałem. 

## Dynamika $r$ przy mierze $\P_T$ cz.2 {.smaller}

Z twierdzenia Girsanowa dostajemy, że
$$W^T_t = W_t^\ast + \int_0^t{n(u,T)\sigma(r_u,u)\,du}$$
zatem SDE przy mierze $\P_T$ na chwilową stopę procentową przedstawia się w następujący sposób:
$$dr_t = \left(\mu(r_t,t) - \sigma^2(r_t,t)\cdot n(t,T)\right)\,dt + \sigma(r_t,t)\,dW^T_t.$$

Zauważmy, że funkcja $\mu$ oraz $\sigma^2$ są funkcjami afinicznymi, zatem z twierdzenia zadającego równoważne warunki na afiniczną strukturę terminową wnioskujemy, że zamiana miary na miarę forward nie zmiania własności afinicznej struktury terminowej.